# Sorting

In [1]:
import time
import numpy as np
np.random.seed(0)

In [16]:
data = np.random.randint(1,10000,17000)

### Insertion Sort

In [8]:
def insertion_sort(arr):
    for i in range(1, len(arr)):
        key = arr[i]
        j = i - 1
        if arr[j] > key:
            while j >= 0 and arr[j] > key:
                arr[j + 1] = arr[j]
                j -= 1
            arr[j + 1] = key
    return arr

In [9]:
arr= insertion_sort(data)

In [10]:
arr

array([   1,    1,    1, ..., 9999, 9999, 9999])

In [11]:
np.flip(arr)

array([9999, 9999, 9999, ...,    1,    1,    1])

### Merge Sort

In [24]:
def merge_sort(arr):
    if len(arr) > 1:
        mid = len(arr)//2
        left = arr[:mid]
        right = arr[mid:]

        # Recursively sort both halves
        merge_sort(left)
        merge_sort(right)

        # Merge the sorted halves
        i = j = k = 0
        while i < len(left) and j < len(right):
            if left[i] < right[j]:
                arr[k] = left[i]
                i += 1
            else:
                arr[k] = right[j]
                j += 1
            k += 1

        # Copy over any remaining elements from the left or right subarray
        while i < len(left):
            arr[k] = left[i]
            i += 1
            k += 1

        while j < len(right):
            arr[k] = right[j]
            j += 1
            k += 1



In [33]:
merge_sort(data)
print(data)

[   1    1    1 ... 7663 7663 7703]


In [41]:
#This method is just to calculate the time, if you don't need it, don't worry
def merge_algorithm(arr):
    start = time.time()
    merge_sort(arr)
    end = time.time()
    
    return print("The time of execution of above program is :", (end-start) * 10**3, "ms", "for a size of ", len(arr))

In [42]:
data = np.random.randint(1,10000,17000)

In [43]:
merge_algorithm(data)

The time of execution of above program is : 228.88946533203125 ms for a size of  17000


Overall, the time complexity of Merge sort is O(n log n), where n is the number of elements in the array being sorted. This is because the merge process takes O(n) time, and we need to perform this process log n times, once for each level of the divide-and-conquer tree.

### Algorithm of your choice

Know implement another algorithm, anyone works. Use the same size of data.

Un subprograma que reciba un número real positivo $(c)$ y un número real positivo cercano a cero $ɛ$, y que devuelva una aproximación del logaritmo natural de $(c)$ a partir del valor dado para $\varepsilon$. El subprograma solicitado debe tener en cuenta que:

\begin{equation}
2∑_{k=0}^n\frac{1}{2k+1}(\frac{c-1}{c+1})^{2k+1}\xrightarrow{n\to∞} ln(c)
\end{equation}

Desrrolllando la serie nos queda que, 
\begin{equation}
ln(c) ≈ 2*((\frac{c-1}{c+1})+\frac{1}{3}(\frac{c-1}{c+1})^3 + \frac{1}{5}(\frac{c-1}{c+1})^5  + ⋯
\end{equation}

Ademas, si $0<c<1$, entonces, 

\begin{equation}
ln(c) = -ln(\frac{1}{c})
\end{equation}

y, si $c>1$, 

\begin{equation}
ln(c) = ln((d)(2^k)) = ln(d) + kln(2)
\end{equation}

In [23]:
def logn(c, eps = 1e-55):   ### The function logn calculates the natural logarithm of a number c.
  ln_2 = 0.6931471805599453   ## The ln_2 variable is assigned the value of the natural logarithm of 2.
  if c == 2:    ## If c is equal to 2, the result is assigned the value of ln_2.
    resul = ln_2   
  elif c < 1:  ## If c is less than 1, the result is assigned the value of the negation of logn applied to the reciprocal of c.
    resul = - logn(1/c)
  elif c > 2:  ## If c is greater than 2, the variable k is initialized to 0 and is incremented by 1 each time c is divided by 2 and is greater than 2. 
    k = 0       
    while c > 2:  
      c /= 2
      k += 1
    resul = logn(c) + k*ln_2  ##The result is then assigned the value of logn of c plus k multiplied by ln_2.
  else:
    frac = (c-1)/(c+1)   ### If c is between 1 and 2 (exclusive), the variable frac is assigned the value of (c-1)/(c+1). 
    den = 1
    num = frac
    resul = frac/den  ## The variable den is initialized to 1 and num to frac. The result is initialized to frac/den. The variable suma is also initialized to frac.
    suma = frac
    while suma > eps:
      num *= frac * frac  ## In a while loop, the value of num is multiplied by frac * frac, the value of den is incremented by 2, suma is updated to the value of num/den, and the result is incremented by suma. The loop continues until suma is less than eps.
      den += 2
      suma = num/den
      resul += suma
    resul *= 2
  
  return resul 

In [24]:
print(logn(16))

2.772588722239781


In [21]:
np.log(16)

2.772588722239781

### Conclusions

So, the algorithm matters! Even when the result is the same, the time it takes is important. We are in the era of Big Data, if we are not careful, some processing might take centuries!